---
- name: (Debian/Ubuntu) Install dependencies
  apt:
    name:
      - gnupg
      - apt-transport-https
    state: present

- name: (Debian/Ubuntu) Add Elasticsearch repository GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  tags: install

- name: (Debian/Ubuntu) Add Elasticsearch 7.X repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    filename: elastic-repo.list
    update_cache: yes
    state: present
  tags: install

- name: (Debian/Ubuntu) Get installed auditbeat version
  command: dpkg-query --showformat='${Version}' --show auditbeat
  register: installed_ab_version
  failed_when: False
  changed_when: False
  check_mode: no
  tags: install

- name: (Debian/Ubuntu) Allow auditbeat to be upgraded
  ansible.builtin.dpkg_selections:
    name: auditbeat
    selection: install
  when:
    installed_ab_version.stdout and installed_ab_version.stdout != auditbeat_service.version
  tags: install

- name: (Debian/Ubuntu) Install auditbeat apt
  apt:
    name: auditbeat={{ auditbeat_service.version }}
    state: present
  tags: install

- name: (Debian/Ubuntu) Prevent auditbeat from being upgraded
  ansible.builtin.dpkg_selections:
    name: auditbeat
    selection: hold
  tags: install
